version: "3.8"

services:
  app:
    build: .
    command: npm run dev
    ports:
      - 3000:3000
    environment:
      - PG_PASSWORD=password
      - PG_DB=market
      - PG_USER=postgres
      - PG_HOST=db
      - SECRET=dbsecret

    volumes:
      - .:/code

  db:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=market

  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
